version: '3.9'

services:
  db_dev:
    image: postgres
    ports:
      - '5432:5432'    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'db_dev:/var/lib/postgresql/data'
  db_test:
    image: postgres
    ports:
      - '5433:5432'    
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
    
volumes:
  db_dev:
