version: '3.9'

services:
  db_dev:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'db_dev:/var/lib/postgresql/data'
volumes:
  db_dev:
