version: '3.9'

services:
  app-test:
    depends_on:
      - database-test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app-test
      - /app-test/node_modules
    ports:
      - 3000:3000

  database-test:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
    ports:
      - 5433:5432
